export enum ACTIONS_TYPE {
  ADD_DATA = 'ADD_DATA',
  ADD_DETAILS = 'ADD_DETAILS',
  ADD_FINANCE_TO_UPDATE = 'ADD_FINANCE_TO_UPDATE',
  UPDATE_FINANCE = 'UPDATE_FINANCE',
  DELETE_FINANCES = 'DELETE_FINANCES',
  ADD_ONE_DATA = 'ADD_ONE_DATA',
}

export type Action<T> = { type: ACTIONS_TYPE; payload?: T };
